apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cnn-serving-cloudlab
  namespace: default
spec:
  template:
    spec:
      containerConcurrency: 1000
      containers:
        - image: macarronesc0lithops/cnn_serving_knative:01
          resources:
            requests:
              cpu: 1000m
              memory: 640M
            limits:
              cpu: 2
    metadata:
      annotations:
        autoscaling.knative.dev/target: "1000"
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "1h"
